export const INITIAL_MEETINGS = [
    {
        id: 1,
        title: "R&I Directorate Strategy Session",
        role: "dir",
        date: new Date().toISOString().split('T')[0],
        start: "09:00",
        end: "10:30",
        location: "Board Room A",
        participants: "Prof. Kariuki, Dr. Mwangi, Dean",
        notes: "Q2 research funding allocations",
        notify: 15,
        status: "pending",
        recur: "none",
        outlook: false
    },
    {
        id: 2,
        title: "MSc Thesis Review — Aisha M.",
        role: "sup",
        date: new Date().toISOString().split('T')[0],
        start: "10:00",
        end: "11:00",
        location: "Office 212",
        participants: "Aisha Mohammed",
        notes: "Chapter 3 methodology review",
        notify: 10,
        status: "pending",
        recur: "none",
        outlook: false
    },
    {
        id: 3,
        title: "Undergraduate Lecture – Res. Methods",
        role: "teach",
        date: new Date().toISOString().split('T')[0],
        start: "11:00",
        end: "13:00",
        location: "Hall B Room 7",
        participants: "BBA Year 3 (46 students)",
        notes: "Topic: Sampling strategies",
        notify: 15,
        status: "done",
        recur: "weekly",
        outlook: true
    },
    {
        id: 4,
        title: "Grant Writing Workshop",
        role: "dir",
        date: new Date().toISOString().split('T')[0],
        start: "14:00",
        end: "16:00",
        location: "Microsoft Teams",
        participants: "Research team + consultants",
        notes: "NSF proposal draft review",
        notify: 30,
        status: "pending",
        recur: "none",
        outlook: true
    },
    {
        id: 5,
        title: "John K. Supervision Session",
        role: "sup",
        date: new Date().toISOString().split('T')[0],
        start: "14:30",
        end: "15:30",
        location: "Office 212",
        participants: "John Kimani",
        notes: "Data analysis discussion",
        notify: 15,
        status: "pending",
        recur: "biweekly",
        outlook: false
    },
    {
        id: 6,
        title: "Faculty Senate Meeting",
        role: "admin",
        date: new Date().toISOString().split('T')[0],
        start: "16:30",
        end: "18:00",
        location: "Senate Chamber",
        participants: "All faculty",
        notes: "Curriculum review agenda",
        notify: 30,
        status: "missed",
        recur: "monthly",
        outlook: true
    }
];

export const ROLES = {
    dir: { label: 'Directorate', icon: '🏛', color: 'gold', className: 'dir' },
    teach: { label: 'Teaching', icon: '📚', color: 'blue', className: 'teach' },
    sup: { label: 'Supervision', icon: '🎓', color: 'orange', className: 'sup' },
    admin: { label: 'Admin', icon: '📋', color: 'purple', className: 'admin' },
};
